[package]
name = "quantum_os"
version = "0.1.0"
edition = "2021"
build="build.rs"

[dependencies]
spin = "0.9.8"
quantum_lib = {path = "../lib/lowlevel_lib" }
bootloader = {path = "../bootloader/bootloader"}
owo-colors = "3.5.0"

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]
